routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::prefix('admin')->group(function () {
    Auth::routes(['register' => true]);

    Route::get('/', 'PostsController@index')->middleware("auth");

    Route::resource('tags', 'TagsController')->except(['show'])->middleware("auth");
    Route::resource('categories', 'CategoriesController')->except(['show'])->middleware("auth");
    Route::resource('images', 'ImagesController')->except(['show'])->middleware("auth");
    Route::resource('posts', 'PostsController')->except(['show'])->middleware("auth");
    Route::resource('pages', 'PagesController')->except(['show'])->middleware("auth");
});

Route::get('/subscribe', "SubscribeController@show")->name("subscribe.result");
Route::post('/subscribe', "SubscribeController@newSubscriber")->name("subscribe.new");
Route::get('/unsubscribe', "SubscribeController@unsubscribe")->name("subscribe.unsubscribe");

Route::get("/post/{slug?}", "PostsController@show")->name("posts.show");
Route::get("/category/{slug?}", "CategoriesController@show")->name("categories.show");
Route::get("/tag/{slug?}", "TagsController@show")->name("tags.show");
Route::get('/{slug?}', "PagesController@show")->name("pages.show");

app/Image.php
<?php

namespace App;

use App\Http\Traits\CategoriesRelation;
use App\Http\Traits\Errors;
use App\Http\Traits\PagesRelation;
use App\Http\Traits\PostsRelation;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use stdClass;

class Image extends Model
{
    use PagesRelation;
    use PostsRelation;
    use CategoriesRelation;

    protected $fillable = ["header", "alt", "filepath"];

    public static function validateImages(Request $request)
    {
        $validatedImages = [];
        if (isset($request->images)) {
            foreach ($request->images as $image) {
                if ($image = Image::find($image)) {
                    $validatedImages[] = $image;
                }
            }
        }

        return $validatedImages;
    }

    /**
     * Check input parameters.
     *
     * @param array $parameters
     * @param string $exceptId
     * @return \Illuminate\Contracts\Validation\Validator
     */
    public function isValid($parameters, $exceptId = '')
    {
        if ($exceptId) {
            $exceptId = ",{$exceptId}";
        }

        $validator = Validator::make($parameters, [
            'header' => "required|max:255|unique:images{$exceptId}",
            'alt' => 'required|max:1000'
        ]);

        return $validator;
    }
}

app/Http/Controllers/ImagesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\MessageBag;
use App\Image;

class ImagesController extends Controller
{
    protected $availableExtensions = [
        "png", "jpg", "jpeg", "gif", "svg"
    ];

    private $errors;

    public function __construct()
    {
        $this->errors = new MessageBag;
    }
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        return view("admin.images.index", [
            "images" => Image::orderBy("id", "ASC")->paginate(15)
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        if (!count($request->file("images"))) {
            $this->errors->add("404", "Files hasn`t been selected.");
            return back()->withErrors($this->errors);
        }

        foreach ($request->file("images") as $image) {
            if (!in_array($image->extension(), $this->availableExtensions)) {
                $this->errors->add("403", "File {$image->getClientOriginalName()} have unavailable file extension");
                return back()->withErrors($this->errors);
            }

            $file = new Image;
            $file->header = $image->getClientOriginalName();
            $file->alt = $image->getClientOriginalName();

            $validation = $file->isValid(
                [
                    "header" => $file->header,
                    "alt" => $file->alt
                ]
            );
            if ($validation->fails()) {
                return back()->withErrors($validation->errors()->all());
            } else {
                try {
                    $path = Storage::disk('public')->putFileAs("images", $image, $image->getClientOriginalName());
                    $file->filepath = $path;
                    $file->save();
                } catch (\Exception $e) {
                    $this->errors->add("500", "File {$image->getClientOriginalName()} couldn`t been saved. Try again...");
                    return back()->withErrors($this->errors);
                }
            }
        }

        return back()->with("status", "File has been uploaded");
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        if (!isset($request->id)) {
            $this->errors->add("419", "Image id hasn`t been founded");
            return back()->withErrors($this->errors);
        }

        $image = Image::find($request->id);

        if (!$image) {
            $this->errors->add("404", "Image hasn`t been founded");
            return back()->withErrors($this->errors);
        }

        $validation = $image->isValid(["header" => $request->header, "alt" => $request->alt], $request->id);
        if ($validation->fails()) {
            return back()->withErrors($validation->errors()->all());
        }

        $image->fill($request->all());
        $image->save();

        return back()->with("status", "Image {$image->header} has been updated");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        $image = Image::find($id);

        if (!$image) {
            $this->errors->add("404", "Image hasn`t been founded");
            return back()->withErrors($this->errors);
        }

        try {
            Storage::disk('public')->delete($image->filepath);
            $image->delete();

            return back()->with("status", "Image #{$id} has been deleted");
        } catch (\Exception $e) {
            $this->errors->add("404", "Image hasn`t been deleted. Try again...");
            return back()->withErrors($this->errors);
        }
    }
}

resources/views/admin/images/index.blade.php
@extends("layouts.admin")

@push("scripts")
<!-- jQuery 1.8 or later, 33 KB -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<!-- Fotorama from CDNJS, 19 KB -->
<link  href="https://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.js"></script>
@endpush

@section("content")
<div class="content">
@foreach ($errors->all() as $error)
<div class="alert alert-warning">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <i class="material-icons">close</i>
    </button>
    <span>
      <b> Внимание - </b> {{ $error }}</span>
  </div>
@endforeach
@if (session('status'))
    <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <i class="material-icons">close</i>
    </button>
    <span>
      <b> Выполнено - </b> {{session('status')}} </span>
  </div>
@endif
<!-- Add images to <div class="fotorama"></div> -->
<div
    class="fotorama"
    data-click="false"
    data-nav="thumbs"
    data-width="100%"
    data-height="70%"
>
@foreach ($images as $image)
<div
    style="width: 100%; height: 100%"
    data-img='/storage/{{ $image->filepath }}'
    data-caption="{{ $image->alt }}"
>
    <form action="{{ route("images.destroy", ["id" => $image->id]) }}" method="POST">
        @csrf
        @method("DELETE")
        <input type="submit" class="btn btn-danger" value="X">
    </form>
    <input
        type="hidden"
        name="id"
        value="{{ $image->id }}"
    >
</div>
@endforeach
</div>

<div class="modal" tabindex="-1" role="dialog" id="changeCaption">
    <form action="{{ route("images.update", ["id" => 0]) }}" method="POST">
        @csrf
        @method("PUT")
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Обновление изображения</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
              <div class="row">
                  <div class="col-md-12">
                      <input id="input__caption" type="text" name="header" class="form-control" placeholder="Введите название изображения...">
                  </div>
                  <div class="col-md-12 mt-3">
                      <input id="input__caption" type="text" name="alt" class="form-control" placeholder="Введите альтернативный текст изображения...">
                  </div>
              </div>
            <input type="hidden" name="id">
          </div>
          <div class="modal-footer">
            <button type="submit" class="btn btn-primary">Сохранить</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
          </div>
        </div>
      </div>
  </form>
</div>

<form action="{{ route("images.store") }}" method="POST" enctype='multipart/form-data'>
    @csrf
    <label class="btn btn-secondary">
        <input class="d-none" type="file" name="images[]" multiple>
        <span>Обзор файлов...</span>
    </label>
    <input class="btn btn-primary" type="submit" value="загрузить">
</form>
    @include('sublayouts.components.pagination', ["data" => $images])
</div>

<script>
    jQuery(document).ready(function() {
        $(".fotorama__caption").dblclick(function() {
            let id = $(this).parents(".fotorama__stage__frame").find("[name=id]").val();

            $("#changeCaption [name=id]").val(id);
            $('#changeCaption').modal('toggle');
        });
    });
</script>
@endsection