routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::prefix('admin')->group(function () {
    Auth::routes(['register' => true]);

    Route::get('/', 'PostsController@index')->middleware("auth");

    Route::resource('tags', 'TagsController')->except(['show'])->middleware("auth");
    Route::resource('categories', 'CategoriesController')->except(['show'])->middleware("auth");
    Route::resource('images', 'ImagesController')->except(['show'])->middleware("auth");
    Route::resource('posts', 'PostsController')->except(['show'])->middleware("auth");
    Route::resource('pages', 'PagesController')->except(['show'])->middleware("auth");
});

Route::get('/subscribe', "SubscribeController@show")->name("subscribe.result");
Route::post('/subscribe', "SubscribeController@newSubscriber")->name("subscribe.new");
Route::get('/unsubscribe', "SubscribeController@unsubscribe")->name("subscribe.unsubscribe");

Route::get("/post/{slug?}", "PostsController@show")->name("posts.show");
Route::get("/category/{slug?}", "CategoriesController@show")->name("categories.show");
Route::get("/tag/{slug?}", "TagsController@show")->name("tags.show");
Route::get('/{slug?}', "PagesController@show")->name("pages.show");

resources/views/layouts/admin.blade.php
<!--
=========================================================
 Material Dashboard - v2.1.1
=========================================================

 Product Page: https://www.creative-tim.com/product/material-dashboard
 Copyright 2019 Creative Tim (https://www.creative-tim.com)
 Licensed under MIT (https://github.com/creativetimofficial/material-dashboard/blob/master/LICENSE.md)

 Coded by Creative Tim

=========================================================

 The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software. -->

<!doctype html>
<html lang="en">

<head>
    <title>@stack('title')</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <!--     Fonts and icons     -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    <!-- Material Kit CSS -->
    <link href="/css/admin/material-dashboard.min.css" rel="stylesheet" />
    <link href="/css/admin/admin.css" rel="stylesheet" />

    @stack('scripts')

    <script src="https://cdn.tiny.cloud/1/j358wes8sc5yld5osrfm1ntzsinsg54alalp87ou9z3r674v/tinymce/5/tinymce.min.js"></script>
    <script>tinymce.init({ selector: ".mce" });</script>
</head>

<body>
    <div class="wrapper ">
      <div class="sidebar" data-color="azure" data-background-color="white" data-image="/img/sidebar-1.jpg">
        <div class="logo">
          <a href="/" class="simple-text logo-normal">
            Сайт
          </a>
        </div>
        <div class="sidebar-wrapper">
          <ul class="nav">
              @php ($url = url()->current())
            <li class="nav-item {{ $url === route("categories.index") || $url === route("categories.create") || $url === route("categories.edit", @$category->id or 1)  ? "active" : "" }}">
              <a class="nav-link" href="{{ route("categories.index") }}">
                <i class="material-icons">Categories</i>
                <p>Категории</p>
              </a>
            </li>
            <li class="nav-item {{ $url === route("tags.index") || $url === route("tags.create") || $url === route("tags.edit", @$tag->id or 1)  ? "active" : "" }}">
              <a class="nav-link" href="{{ route("tags.index") }}">
                <i class="material-icons">Tags</i>
                <p>Теги</p>
              </a>
            </li>
            <li class="nav-item {{ $url === route("posts.index") || $url === route("posts.create") || $url === route("posts.edit", @$post->id or 1)  ? "active" : "" }}">
              <a class="nav-link" href="{{ route("posts.index") }}">
                <i class="material-icons">Posts</i>
                <p>Посты</p>
              </a>
            </li>
            <li class="nav-item {{ $url === route("pages.index") || $url === route("pages.create") || $url === route("pages.edit", @$page->id or 1)  ? "active" : "" }}">
              <a class="nav-link" href="{{ route("pages.index") }}">
                <i class="material-icons">Pages</i>
                <p>Страницы</p>
              </a>
            </li>
            <li class="nav-item {{ $url === route("images.index")  ? "active" : "" }}">
              <a class="nav-link" href="{{ route("images.index") }}">
                <i class="material-icons">Image</i>
                <p>Изображения</p>
              </a>
            </li>
              <li class="nav-item d-flex justify-content-center">
                  <form action="{{ route("logout") }}" method="POST">
                      @csrf
                      <input type="submit" class="btn btn-secondary" value="Выйти">
                    </form>
            </li>
          </ul>
        </div>
      </div>
      <div class="main-panel">
        <!-- End Navbar -->
        @yield("content")
        <footer class="footer">
            @yield("footer")
        </footer>
      </div>
    </div>
    <!--   Core JS Files   -->
    <script src="/js/core/jquery.min.js"></script>
    <script src="/js/core/popper.min.js"></script>
    <script src="/js/core/bootstrap-material-design.min.js"></script>
    <script src="/js/plugins/perfect-scrollbar.jquery.min.js"></script>
    <!-- Plugin for the momentJs  -->
    <script src="/js/plugins/moment.min.js"></script>
    <!--  Plugin for Sweet Alert -->
    <script src="/js/plugins/sweetalert2.js"></script>
    <!-- Forms Validations Plugin -->
    <script src="/js/plugins/jquery.validate.min.js"></script>
    <!-- Plugin for the Wizard, full documentation here: https://github.com/VinceG/twitter-bootstrap-wizard -->
    <script src="/js/plugins/jquery.bootstrap-wizard.js"></script>
    <!--	Plugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select -->
    <script src="/js/plugins/bootstrap-selectpicker.js"></script>
    <!--  Plugin for the DateTimePicker, full documentation here: https://eonasdan.github.io/bootstrap-datetimepicker/ -->
    <script src="/js/plugins/bootstrap-datetimepicker.min.js"></script>
    <!--  DataTables.net Plugin, full documentation here: https://datatables.net/  -->
    <script src="/js/plugins/jquery.dataTables.min.js"></script>
    <!--	Plugin for Tags, full documentation here: https://github.com/bootstrap-tagsinput/bootstrap-tagsinputs  -->
    <script src="/js/plugins/bootstrap-tagsinput.js"></script>
    <!-- Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput -->
    <script src="/js/plugins/jasny-bootstrap.min.js"></script>
    <!--  Full Calendar Plugin, full documentation here: https://github.com/fullcalendar/fullcalendar    -->
    <script src="/js/plugins/fullcalendar.min.js"></script>
    <!-- Vector Map plugin, full documentation here: http://jvectormap.com/documentation/ -->
    <script src="/js/plugins/jquery-jvectormap.js"></script>
    <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
    <script src="/js/plugins/nouislider.min.js"></script>
    <!-- Include a polyfill for ES6 Promises (optional) for IE11, UC Browser and Android browser support SweetAlert -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.js"></script>
    <!-- Library for adding dinamically elements -->
    <script src="/js/plugins/arrive.min.js"></script>
    <!--  Google Maps Plugin    -->
    <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
    <!-- Chartist JS -->
    <script src="/js/plugins/chartist.min.js"></script>
    <!--  Notifications Plugin    -->
    <script src="/js/plugins/bootstrap-notify.js"></script>
    <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
    <script src="/js/material-dashboard.js?v=2.1.1" type="text/javascript"></script>
    <script>
      $(document).ready(function() {
        // Javascript method's body can be found in assets/js/demos.js
        md.initDashboardPageCharts();
      });
    </script>
</body>

</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/public.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@stack('seo_title')</title>
    <meta name="description" content="@stack('seo_description')">
    <meta name="keywords" content="@stack('seo_keywords')">

    @include('sublayouts.libs.jquery')
    @include('sublayouts.libs.popper')
    @include('sublayouts.libs.bootstrap')

    <!--Fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500,700,900" rel="stylesheet">
    <link href="{{ asset('/fonts/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet">

    <!--Styles-->
    <link rel="stylesheet" href="{{ asset('/css/public/main.css') }}">
    <link rel="stylesheet" href="{{ asset('/css/public/menu.css') }}">
    <link rel="stylesheet" href="{{ asset('/css/public/search.css') }}">
    <link rel="stylesheet" href="{{ asset('/css/public/footer.css') }}">

    @stack('styles')

    @stack('scripts')
</head>
<body>
    <nav>
        <div class="container">
            <div class="row">
                <div class="col-md-12 d-flex justify-content-center">
                    @include('sublayouts.menu.top')
                    @include('sublayouts.menu.mobile')
                </div>
            </div>
        </div>
    </nav>
    <main>
        <div class="container-fluid mt-5 p-0">
            <div class="row">
                <div class="col-md-12 text-center">
                    <a href="/">
                    @include('sublayouts.components.logo')
                    </a>
                </div>
            </div>
        </div>
    @yield('content')
    </main>
    <footer>
        <div class="container-fluid">
            <div class="row">
                <div class="col-12 text-center">
                    @include('sublayouts.components.footerLogo')
                </div>
            </div>
            <div class="row justify-content-center mt-5">
                <div class="col-md-5">
                    @include('sublayouts.components.footerText')
                </div>
            </div>
            <div class="row justify-content-center mt-3">
                <div class="col-md-5">
                    @include('sublayouts.components.footerCopyright')
                </div>
            </div>
        </div>
    </footer>

    @include('sublayouts.dev.livereload')
</body>
</html>