routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::prefix('admin')->group(function () {
    Auth::routes(['register' => true]);

    Route::get('/', 'PostsController@index')->middleware("auth");

    Route::resource('tags', 'TagsController')->except(['show'])->middleware("auth");
    Route::resource('categories', 'CategoriesController')->except(['show'])->middleware("auth");
    Route::resource('images', 'ImagesController')->except(['show'])->middleware("auth");
    Route::resource('posts', 'PostsController')->except(['show'])->middleware("auth");
    Route::resource('pages', 'PagesController')->except(['show'])->middleware("auth");
});

Route::get('/subscribe', "SubscribeController@show")->name("subscribe.result");
Route::post('/subscribe', "SubscribeController@newSubscriber")->name("subscribe.new");
Route::get('/unsubscribe', "SubscribeController@unsubscribe")->name("subscribe.unsubscribe");

Route::get("/post/{slug?}", "PostsController@show")->name("posts.show");
Route::get("/category/{slug?}", "CategoriesController@show")->name("categories.show");
Route::get("/tag/{slug?}", "TagsController@show")->name("tags.show");
Route::get('/{slug?}', "PagesController@show")->name("pages.show");

app/Tag.php
<?php

namespace App;

use App\Http\Traits\PostsRelation;
use App\Http\Traits\Settings;
use App\Http\Traits\TemplatesRelation;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class Tag extends Model
{
    use Settings;
    use PostsRelation;
    use TemplatesRelation;

    protected $fillable = [
        "header", "slug", "seo_title", "seo_keywords", "seo_description", "description", "settings"
    ];

    public static function validateTags(Request $request)
    {
        $validatedTags = [];
        if (isset($request->tags)) {
            foreach ($request->tags as $tagId) {
                if ($tag = Tag::find($tagId)) {
                    $validatedTags[] = $tag;
                }
            }
        }

        return $validatedTags;
    }

    /**
     * Check input parameters.
     *
     * @param Request $request
     * @param string $exceptId
     * @return bool
     */
    public function isValid(Request $request, $exceptId = '')
    {
        if ($exceptId) {
            $exceptId = ",{$exceptId}";
        }

        $validator = Validator::make($request->all(), [
            'header' => 'required|max:255',
            'slug' => "required|max:191|alpha_dash|unique:tags,slug{$exceptId}",
            'seo_title' => 'max:255|nullable',
            'seo_keywords' => 'max:500|nullable',
            'seo_description' => 'max:500|nullable',
            'description' => 'max:10000|nullable',
            'template_id' => 'required|integer',
            'posts_count_on_page' => 'integer|nullable',
            'recent_posts_count' => 'integer|nullable',
            'featured_posts_count' => 'integer|nullable',
            'tags_count' => 'integer|nullable',
            'categories_count' => 'integer|nullable',
        ]);

        return $validator;
    }

    /**
     * Return tags.
     *
     * @param $tagsCount
     * @return Category
     */
    public static function getTags($tagsCount)
    {
        return Tag::inRandomOrder()->take($tagsCount)->get();
    }
}

app/Http/Controllers/TagsController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Traits\Errors;
use App\Http\Traits\Views;
use App\Page;
use App\Post;
use App\Tag;
use App\Template;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\MessageBag;
use Carbon\Carbon;

class TagsController extends Controller
{
    use Errors;
    use Views;

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        return view("admin.tags.index", [
            "tags" => Tag::orderBy("id", "ASC")->paginate(15)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param Request $request
     * @return Response
     */
    public function create(Request $request)
    {
        return view("admin.tags.create", [
            "templates" => Template::get()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        $tag = new Tag;

        $validation = $tag->isValid($request);
        if (!$validation->fails()) {
            $tag->fill($request->all());
            $tag->updateSettings($request->all());

            if (!$template = Template::find($request->template_id)) {
                $this->errors->add('404', "Template #{$request->template_id} hasn`t been found");
                return back()->withInput()->withErrors($this->errors);
            }

            $tag->template()->associate($template);
            $tag->save();

            return redirect()->route("tags.index")->with("status", "Tag #{$tag->id} has been created");
        } else {
            return back()->withInput()->withErrors($validation->errors()->all());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param Request $request
     * @param $slug
     * @return Response
     */
    public function show(Request $request, $slug)
    {
        $tag = Tag::where("slug", "=", $slug)->first();

        if (!$tag) {
            return abort(404);
        }
        $tag->parseSettings();

        try {
            return view($this->getView($tag), [
                "tag" => $tag,
                "pages" => Page::getPages(),
                "categories" => Category::getCategories($tag->settings->categories_count),
                "posts" => $tag->postsMany()->paginate($tag->settings->posts_count_on_page),
                "recentPosts" => Post::getRecentPosts($tag->settings->recent_posts_count),
                "tags" => Tag::getTags($tag->settings->tags_count)
            ]);
        } catch (\Exception $e) {
            return abort(404);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Request $request
     * @param int $id
     * @return Response
     */
    public function edit(Request $request, $id)
    {
        $tag = Tag::find($id);

        if (!$tag) {
            $this->errors->add("404", "Tag #{$id} hasn`t been found");
            return back()->withErrors($this->errors);
        } else {
            return view("admin.tags.edit", [
                "tag" => $tag,
                "templates" => Template::get()
            ]);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $tag = Tag::find($id);

        if (!$tag) {
            $this->errors->add("404", "Tag $id hasn`t been found");
            return back()->withErrors($this->errors);
        }

        $validation = $tag->isValid($request, $id);
        if (!$validation->fails()) {
            $tag->fill($request->all());
            $tag->updateSettings($request->all());

            if (!$template = Template::find($request->template_id)) {
                $this->errors->add('404', "Template #{$request->template_id} hasn`t been found");
                return back()->withInput()->withErrors($this->errors);
            }

            $tag->template()->associate($template);
            $tag->save();

            return redirect()->route("tags.index")->with("status", "Tag #{$tag->id} has been updated");
        } else {
            return back()->withInput()->withErrors($validation->errors()->all());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        $tag = Tag::find($id);

        if (!$tag) {
            $this->errors->add("404", "Tag #$id hasn`t been found");
            return back()->withErrors($this->errors);
        } else {
            $tag->delete();
            return back()->with("status", "Tag #{$id} was deleted");
        }
    }
}

resources/views/admin/tags/create.blade.php
@extends("layouts.admin")

@push('title')
    Создание тега
@endpush

@section("content")
<div class="content">
    @foreach ($errors->all() as $error)
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <i class="material-icons">close</i>
        </button>
        <span>
          <b> Внимание - </b> {{ $error }}</span>
      </div>
    @endforeach
    @if (session('status'))
        <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <i class="material-icons">close</i>
        </button>
        <span>
          <b> Выполнено - </b> {{session('status')}} </span>
      </div>
    @endif
    <form action="{{ route("tags.store") }}" method="POST">
        @csrf
      <div class="container-fluid">
        <div class="row justify-content-center">
          <div class="col-md-10">
            <div class="card">
              <div class="card-header card-header-primary">
                <h4 class="card-title">Создание тега</h4>
              </div>
              <div class="card-body">
                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          <label class="bmd-label-floating">Заголовок</label>
                          <input type="text" class="form-control" name="header" value="{{ old("header") }}">
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          <label class="bmd-label-floating">Алиас</label>
                          <input type="text" class="form-control" name="slug" value="{{ old("slug") }}">
                        </div>
                      </div>
                    </div>
                    @if ($templates->count())
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="template_id" class="bmd-label-floating">Шаблон</label>
                                    <select id="template_id" name="template_id" class="form-control">
                                        @foreach($templates as $template)
                                            <option value="{{ $template->id }}" {{ ($template->id == old("template_id") ? "selected" : "") }}>{{ $template->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>
                    @endif
                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          <label class="bmd-label-floating">Seo-заголовок</label>
                          <input type="text" class="form-control" name="seo_title"  value="{{ old("seo_title") }}">
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          <label class="bmd-label-floating">Ключевые слова</label>
                          <input type="text" class="form-control" name="seo_keywords"  value="{{ old("seo_keywords") }}">
                        </div>
                      </div>
                    </div>
                  <div class="row">
                    <div class="col-md-12">
                      <div class="form-group">
                        <label>Seo-описание</label>
                        <div class="form-group">
                          <textarea class="form-control" rows="5" name="seo_description" value="{{ old("seo_description") }}">{{ old("seo_description") }}</textarea>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-12">
                      <div class="form-group">
                        <label>Описание</label>
                        <div class="form-group">
                          <textarea class="form-control mce" rows="20" name="description" value="{{ old("description") }}">{{ old("description") }}</textarea>
                        </div>
                      </div>
                    </div>
                  </div>
                  <button type="submit" class="btn btn-primary pull-right">Создать</button>
                  <a href="{{ route("tags.index") }}" class="btn btn-success" onclick="return confirm('Вы уверены?')">Вернуться</a>
                  <div class="clearfix"></div>
              </div>
            </div>
              <div class="collapse show" id="collapseExample">
                  <div class="card card-body">
                      <div class="form-group">
                          <label class="bmd-label-floating">Количество постов на странице</label>
                          <input
                              type="number"
                              class="form-control"
                              name="posts_count_on_page"
                              value="{{ old("posts_count_on_page") ? old("posts_count_on_page") : POSTS_COUNT_ON_PAGE }}">
                      </div>
                      <div class="form-group">
                          <label class="bmd-label-floating">Recent posts count</label>
                          <input
                              type="number"
                              class="form-control"
                              name="recent_posts_count"
                              value="{{ old("recent_posts_count") ? old("recent_posts_count") : RECENT_POSTS_COUNT }}">
                      </div>
                      <div class="form-group">
                          <label class="bmd-label-floating">Количество избранных постов на странице</label>
                          <input
                              type="number"
                              class="form-control"
                              name="featured_posts_count"
                              value="{{ old("featured_posts_count") ? old("featured_posts_count") : FEATURED_POSTS_COUNT }}">
                      </div>
                      <div class="form-group">
                          <label class="bmd-label-floating">Количество тегов</label>
                          <input
                              type="number"
                              class="form-control"
                              name="tags_count"
                              value="{{ old("tags_count") ? old("tags_count") : TAGS_COUNT }}">
                      </div>
                      <div class="form-group">
                          <label class="bmd-label-floating">Количество категорий</label>
                          <input
                              type="number"
                              class="form-control"
                              name="categories_count"
                              value="{{ old("categories_count") ? old("categories_count") : CATEGORIES_COUNT }}">
                      </div>
                  </div>
              </div>
          </div>
        </div>
      </div>
  </form>
</div>
@endsection

resources/views/admin/tags/edit.blade.php
@extends("layouts.admin")

@push('title')
    #{{ $tag->id }} {{ $tag->header }} - редактирование
@endpush

@section("content")
<div class="content">
    @foreach ($errors->all() as $error)
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <i class="material-icons">close</i>
        </button>
        <span>
          <b> Внимание - </b> {{ $error }}</span>
      </div>
    @endforeach
    @if (session('status'))
        <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <i class="material-icons">close</i>
        </button>
        <span>
          <b> Выполнено - </b> {{session('status')}} </span>
      </div>
    @endif
    <form action="{{ route("tags.update", ['id' => $tag->id ]) }}" method="POST">
        @csrf
        @method("PUT")
      <div class="container-fluid">
        <div class="row justify-content-center">
          <div class="col-md-10">
            <div class="card">
              <div class="card-header card-header-primary">
                <h4 class="card-title">Обновление тега #{{ $tag->id }}</h4>
              </div>
              <div class="card-body">
                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          <label class="bmd-label-floating">Заголовок</label>
                          <input type="text" class="form-control" name="header" value="{{ $tag->header }}">
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          <label class="bmd-label-floating">Алиас</label>
                          <input type="text" class="form-control" name="slug" value="{{ $tag->slug }}">
                        </div>
                      </div>
                    </div>
                    @if ($templates->count())
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="template_id" class="bmd-label-floating">Шаблон</label>
                                    <select id="template_id" name="template_id" class="form-control">
                                        @foreach($templates as $template)
                                            <option value="{{ $template->id }}" {{ ($tag->template()->first() && $template->id == $tag->template()->first()->id ? "selected" : "") }}>{{ $template->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>
                    @endif
                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          <label class="bmd-label-floating">Seo-заголовок</label>
                          <input type="text" class="form-control" name="seo_title"  value="{{ $tag->seo_title }}">
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          <label class="bmd-label-floating">Ключевые слова</label>
                          <input type="text" class="form-control" name="seo_keywords"  value="{{ $tag->seo_keywords }}">
                        </div>
                      </div>
                    </div>
                  <div class="row">
                    <div class="col-md-12">
                      <div class="form-group">
                        <label>Seo-описание</label>
                        <div class="form-group">
                          <textarea class="form-control" rows="5" name="seo_description" value="{{ $tag->seo_description }}">{{ $tag->seo_description }}</textarea>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-12">
                      <div class="form-group">
                        <label>Описание</label>
                        <div class="form-group">
                          <textarea class="form-control mce" rows="5" name="description" value="{{ $tag->description }}">{{ $tag->description }}</textarea>
                        </div>
                      </div>
                    </div>
                  </div>
                  <button type="submit" class="btn btn-primary pull-right">Обновить</button>
                  <a href="{{ route("tags.index") }}" class="btn btn-success" onclick="return confirm('Вы уверены?')">Вернуться</a>
                  <div class="clearfix"></div>
              </div>
            </div>
              <div class="collapse show" id="collapseExample">
                  <div class="card card-body">
                      <div class="form-group">
                          <label class="bmd-label-floating">Количество постов на странице</label>
                          <input
                              type="number"
                              class="form-control"
                              name="posts_count_on_page"
                              value="{{ isset($tag->settings->posts_count_on_page) ? $tag->settings->posts_count_on_page : POSTS_COUNT_ON_PAGE }}">
                      </div>
                      <div class="form-group">
                          <label class="bmd-label-floating">Количество недавно добавленных постов на странице</label>
                          <input
                              type="number"
                              class="form-control"
                              name="recent_posts_count"
                              value="{{ isset($tag->settings->recent_posts_count) ? $tag->settings->recent_posts_count : RECENT_POSTS_COUNT }}">
                      </div>
                      <div class="form-group">
                          <label class="bmd-label-floating">Количество избранных постов</label>
                          <input
                              type="number"
                              class="form-control"
                              name="featured_posts_count"
                              value="{{ isset($tag->settings->featured_posts_count) ? $tag->settings->featured_posts_count : FEATURED_POSTS_COUNT }}">
                      </div>
                      <div class="form-group">
                          <label class="bmd-label-floating">Количество тегов</label>
                          <input
                              type="number"
                              class="form-control"
                              name="tags_count"
                              value="{{ isset($tag->settings->tags_count) ? $tag->settings->tags_count : TAGS_COUNT }}">
                      </div>
                      <div class="form-group">
                          <label class="bmd-label-floating">Количество категорий</label>
                          <input
                              type="number"
                              class="form-control"
                              name="subcategories_count"
                              value="{{ isset($tag->settings->categories_count) ? $tag->settings->categories_count : CATEGORIES_COUNT }}">
                      </div>
                  </div>
              </div>
          </div>
        </div>
      </div>
  </form>
</div>
@endsection

resources/views/admin/tags/index.blade.php
@extends("layouts.admin")

@push('title')
    Список тегов
@endpush

@section("content")
<div class="content">
    @foreach ($errors->all() as $error)
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <i class="material-icons">close</i>
        </button>
        <span>
          <b> Внимание - </b> {{ $error }}</span>
      </div>
    @endforeach
    @if (session('status'))
        <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <i class="material-icons">close</i>
        </button>
        <span>
          <b> Выполнено - </b> {{session('status')}} </span>
      </div>
    @endif
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card card-plain">
            <div class="card-header card-header-primary">
              <h4 class="card-title mt-0">Теги</h4>
            </div>
          <div class="card-body">
              <div class="d-flex justify-content-end">
                  <a href="{{ route("tags.create") }}" class="btn btn-success">Добавить</a>
              </div>
            <div class="table-responsive">
              <table class="table table-hover">
                <thead class="">
                  <th>
                    ID
                  </th>
                  <th>
                    Заголовок
                  </th>
                  <th>
                    Алиас
                  </th>
                  <th>
                    Seo-заголовок
                  </th>
                  <th>
                    Ключевые слова
                  </th>
                  <th>
                    Seo-описание
                  </th>
                  <th>Действия</th>
                </thead>
                <tbody>
                    @foreach($tags as $tag)
                    <tr>
                      <td>
                        {{ $tag->id }}
                      </td>
                      <td>
                          <a href="{{ route("tags.show", $tag->slug) }}">{{ $tag->header }}</a>
                      </td>
                      <td>
                        {{ $tag->slug }}
                      </td>
                      <td>
                        {{ $tag->seo_title }}
                      </td>
                      <td>
                        {{ $tag->seo_keywords }}
                      </td>
                      <td>
                        {{ $tag->seo_description }}
                      </td>
                      <td class="td-actions text-right d-flex">
                        <button type="button" rel="tooltip" title="" class="btn btn-primary btn-link btn-sm" data-original-title="Редактировать" aria-describedby="tooltip803439">
                          <a href="{{ route("tags.edit", ["id" => $tag->id]) }}"><i class="material-icons">edit</i></a>
                        </button>
                        <form action="{{ route("tags.destroy", ["id" => $tag->id]) }}" method="POST" onsubmit="return confirm('Вы действительно хотите удалить тег #{{ $tag->id }}')">
                            @csrf
                            @method("DELETE")
                            <button type="submit" rel="tooltip" title="" class="btn btn-danger btn-link btn-sm" data-original-title="Удалить">
                              <i class="material-icons">close</i>
                            </button>
                        </form>
                      </td>
                    </tr>
                    @endforeach
                </tbody>
              </table>
              @if (!count($tags))
              <div class="alert alert-info" role="alert">
                Теги не найдены
              </div>
              @endif
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
    @include('sublayouts.components.pagination', ["data" => $tags])
</div>
@endsection